---
title: "SW and ADF test (Inflation)"
author: "Shuofan Zhang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---

## ADF test  

Step 1, ADF test to the 146 original series.

Step 2, mark "I(0)" variables as "I(0)".

Step 3, ADF test to the first-differenced 146 series.

Step 4, check for contradictions, found "PCED_RecServices" in AIC.

Step 5, mark "I(1)" variable as "I(2)" (including "PCED_RecServices").

Step 6, mark the rest as "I(1)".

Step 7, repeat the above 6 steps for both "AIC" and "BIC".


```{r, echo=F, message=F, warning=F}
load("sab_gdp.RData")
```

## Lasso 1  

$$ 
\begin{split} 
\Delta y_t &=y_{t-1} \\
&+ \Delta y_{t-1} + \Delta y_{t-2} + \Delta y_{t-3} + \Delta y_{t-4} \\
&+  I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  I(1)_{t-1} +  I(1)_{t-2} 
+  I(1)_{t-3} +  I(1)_{t-4} \\
&+  \Delta I(2)_{t-1} +  \Delta I(2)_{t-2} 
+  \Delta I(2)_{t-3} +  \Delta I(2)_{t-4}
\end{split} 
$$

```{r include=T, message=F, warning=F, echo=F}
# SW
lasso1.sw = lasso111(data = bpraw, tcode = t.sw)
trace1.sw = trace.plot.table(lasso1.sw$lasso, lambda.seq, lasso1.sw$lambda)
# AIC
lasso1.aic = lasso111(data = bpraw, tcode = t.aic)
trace1.aic = trace.plot.table(lasso1.aic$lasso, lambda.seq, lasso1.aic$lambda)
# BIC
lasso1.bic = lasso111(data = bpraw, tcode = t.bic)
trace1.bic = trace.plot.table(lasso1.bic$lasso, lambda.seq, lasso1.bic$lambda)

sum1 = sumtable(trace1.sw, trace1.aic, trace1.bic)
sum1 = cbind(I1 = c("", "", "AIC, BIC", "SW, AIC", "", "SW, AIC"), sum1)
colnames(sum1) = c("I(1)", "S & W", "AIC", "BIC")
pander(sum1, caption = "Lasso 1, non-zero coefficients")
```

## Lasso 2  

$$ 
\begin{split} 
\Delta y_t &=y_{t-1} \\
&+ \Delta y_{t-1} + \Delta y_{t-2} + \Delta y_{t-3} + \Delta y_{t-4} \\
&+  I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  \Delta I(1)_{t-1} +  \Delta I(1)_{t-2} 
+  \Delta I(1)_{t-3} +  \Delta I(1)_{t-4} \\
&+  \Delta^2 I(2)_{t-1} +  \Delta^2 I(2)_{t-2} 
+  \Delta^2 I(2)_{t-3} +  \Delta^2 I(2)_{t-4}
\end{split} 
$$


```{r include=T, message=F, warning=F, echo=F}
# SW
lasso2.sw = lasso222(data = bpraw, tcode = t.sw)
trace2.sw = trace.plot.table(lasso2.sw$lasso, lambda.seq, lasso2.sw$lambda)
# AIC
lasso2.aic = lasso222(data = bpraw, tcode = t.aic)
trace2.aic = trace.plot.table(lasso2.aic$lasso, lambda.seq, lasso2.aic$lambda)
# BIC
lasso2.bic = lasso222(data = bpraw, tcode = t.bic)
trace2.bic = trace.plot.table(lasso2.bic$lasso, lambda.seq, lasso2.bic$lambda)

sum2 = sumtable(trace2.sw, trace2.aic, trace2.bic)
colnames(sum2) = c("I(1)", "S & W", "AIC", "BIC")
pander(sum2, caption = "Lasso 2, non-zero coefficients")
```

## Lasso 3

$$ 
\begin{split} 
\Delta y_t &=y_{t-1} \\
&+ \Delta y_{t-1} + \Delta y_{t-2} + \Delta y_{t-3} + \Delta y_{t-4} \\
&+  I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  \Delta I(1)_{t-1} +  \Delta I(1)_{t-2} 
+  \Delta I(1)_{t-3} +  \Delta I(1)_{t-4} \\
&+  \Delta^2 I(2)_{t-1} +  \Delta^2 I(2)_{t-2} 
+  \Delta^2 I(2)_{t-3} +  \Delta^2 I(2)_{t-4} \\
&+ I(1)_{t-1} + \Delta I(2)_{t-1}
\end{split} 
$$

```{r include=T, message=F, warning=F, echo=F}
# SW
lasso3.sw = lasso333(data = bpraw, tcode = t.sw)
trace3.sw = trace.plot.table(lasso3.sw$lasso, lambda.seq, lasso3.sw$lambda)
# AIC
lasso3.aic = lasso333(data = bpraw, tcode = t.aic)
trace3.aic = trace.plot.table(lasso3.aic$lasso, lambda.seq, lasso3.aic$lambda)
# BIC
lasso3.bic = lasso333(data = bpraw, tcode = t.bic)
trace3.bic = trace.plot.table(lasso3.bic$lasso, lambda.seq, lasso3.bic$lambda)

sum3 = sumtable(trace3.sw, trace3.aic, trace3.bic)
sum3 = cbind(I1 = c("",  "AIC, BIC", "", "", "", "", ""), sum3)
colnames(sum3) = c("I(1)", "S & W", "AIC", "BIC")
pander(sum3, caption = "Lasso 3, non-zero coefficients")
```







