---
title: "NG and ADF test (excess return)"
author: "Shuofan Zhang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---

# Data

Data: 131-8=123 series in total, 480 observations, from Jan 1964 to Dec 2003.

The "spread" series (difference between two I(1) series) are removed.

log() is done.

ADF test suggest I(0) for all four bond returns, whether use "trend" or "drift" specification.

# Lasso 1

I(2) is first differenced, others are original.

$$ 
\begin{split} 
y_t &= I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  I(1)_{t-1} +  I(1)_{t-2} 
+  I(1)_{t-3} +  I(1)_{t-4} \\
&+  \Delta I(2)_{t-1} +  \Delta I(2)_{t-2} 
+  \Delta I(2)_{t-3} +  \Delta I(2)_{t-4}
\end{split} 
$$
# Lasso 2

All stationary.

$$ 
\begin{split} 
y_t &= I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  \Delta I(1)_{t-1} +  \Delta I(1)_{t-2} 
+  \Delta I(1)_{t-3} +  \Delta I(1)_{t-4} \\
&+  \Delta^2 I(2)_{t-1} +  \Delta^2 I(2)_{t-2} 
+  \Delta^2 I(2)_{t-3} +  \Delta^2 I(2)_{t-4}
\end{split} 
$$
# Lasso 3

Combination of Lasso 1 and 2.

$$ 
\begin{split} 
y_t &=I(0)_{t-1} +  I(0)_{t-2} 
+  I(0)_{t-3} +  I(0)_{t-4} \\
&+  \Delta I(1)_{t-1} +  \Delta I(1)_{t-2} 
+  \Delta I(1)_{t-3} +  \Delta I(1)_{t-4} \\
&+  \Delta^2 I(2)_{t-1} +  \Delta^2 I(2)_{t-2} 
+  \Delta^2 I(2)_{t-3} +  \Delta^2 I(2)_{t-4} \\
&+ I(1)_{t-1} + \Delta I(2)_{t-1}
\end{split} 
$$

```{r, include=T, echo=F, warning=F, 	message = FALSE}
library("glmnet")
library("reshape2")
library("cellranger")
library("tidyverse")
library("knitr")
library("ggrepel")
library("pander")
library("kableExtra")
library("tseries")
library("urca")
library("lmtest")
library("zoo")
load("/Users/stanza/documents/github/lasso/ng/ngdata.RData")
source("/Users/stanza/documents/github/lasso/fun.R")
### ng raw data was from 1960.1 - 2007.12 (now truncated to 1964.1-2003.12)
### ydata (return) is from 1964.1 - 2003.12
maxlag = 25

lambda.seq <- seq(0.5, 0, -0.0025)
lambda.seq.fd <- seq(0.2, 0, -0.001)

xx = as.yearmon(1964 + seq(0, 479)/12) 
l = ceiling(dim(ydata)[1]*0.8)
ggplot(data=ydata, aes(x=xx, y=yr2)) + geom_line() + geom_vline(xintercept=xx[l], color="red") +
  scale_x_continuous(breaks = seq(1964, 2003, by=3)) +
  xlab("Year") + ylab("Excess Bond Return (yr2)")

aic.trend = adf.auto(as.data.frame(ydata[,-5]), criteria = "AIC")
bic.trend = adf.auto(as.data.frame(ydata[,-5]), criteria = "BIC")
aic.drift = adf.drift(as.data.frame(ydata[,-5]), criteria = "AIC")
bic.drift = adf.drift(as.data.frame(ydata[,-5]), criteria = "BIC")
adftests = rbind(cbind(aic.trend, bic.trend), cbind(aic.drift, bic.drift)) 
```

```{r include=T, message=F, warning=F, echo=F}
sum.total = rep(NA, 4)
mses = list()
for (i in 2:5) {
  yr = ydata[,(i-1)] %>% unlist()
  train1.ng = ng1train(data = ngraw, tcode = t.ng, yr=yr)
  train1.aic = ng1train(data = ngraw, tcode = t.aic, yr=yr)
  train1.bic = ng1train(data = ngraw, tcode = t.bic, yr=yr)
  trace1.ng = trace.plot.table(train1.ng$lasso, lambda.seq, train1.ng$lambda)
  trace1.aic = trace.plot.table(train1.aic$lasso, lambda.seq, train1.aic$lambda)
  trace1.bic = trace.plot.table(train1.bic$lasso, lambda.seq, train1.bic$lambda)
  sum1 = sumtable(trace1.ng, trace1.aic, trace1.bic)
  title1 = c("LASSO 1", rep(paste0("yr",i),3))
  sum1 = rbind(title1, sum1)
  MSE1 = c(train1.ng$mse, train1.aic$mse, train1.bic$mse)
  train2.ng = ng2train(data = ngraw, tcode = t.ng, yr=yr)
  train2.aic = ng2train(data = ngraw, tcode = t.aic, yr=yr)
  train2.bic = ng2train(data = ngraw, tcode = t.bic, yr=yr)
  trace2.ng = trace.plot.table(train2.ng$lasso, lambda.seq, train2.ng$lambda)
  trace2.aic = trace.plot.table(train2.aic$lasso, lambda.seq, train2.aic$lambda)
  trace2.bic = trace.plot.table(train2.bic$lasso, lambda.seq, train2.bic$lambda)
  sum2 = sumtable(trace2.ng, trace2.aic, trace2.bic)
  title2 = c("LASSO 2", rep(paste0("yr",i),3))
  sum2 = rbind(title2, sum2)
  MSE2 = c(train2.ng$mse, train2.aic$mse, train2.bic$mse)
  train3.ng = ng3train(data = ngraw, tcode = t.ng, yr=yr)
  train3.aic = ng3train(data = ngraw, tcode = t.aic, yr=yr)
  train3.bic = ng3train(data = ngraw, tcode = t.bic, yr=yr)
  trace3.ng = trace.plot.table(train3.ng$lasso, lambda.seq, train3.ng$lambda)
  trace3.aic = trace.plot.table(train3.aic$lasso, lambda.seq, train3.aic$lambda)
  trace3.bic = trace.plot.table(train3.bic$lasso, lambda.seq, train3.bic$lambda)
  sum3 = sumtable(trace3.ng, trace3.aic, trace3.bic)
  title3 = c("LASSO 3", rep(paste0("yr",i),3))
  sum3 = rbind(title3, sum3)
  MSE3 = c(train3.ng$mse, train3.aic$mse, train3.bic$mse)
  sum.total = rbind(sum.total, sum1, sum2, sum3)
  mses = rbind(mses, MSE1, MSE2, MSE3)
}
write.csv(sum.total, paste0("/Users/stanza/documents/github/lasso/ng/yr2345.csv"))
write.csv(mses, paste0("/Users/stanza/documents/github/lasso/ng/mse_yr.csv"))
```



```{r include=T, message=F, warning=F, echo=F}
p = vector(length = 4)
mse = vector(length = 4)
ar.list = as.data.frame(matrix(NA, ncol =8, nrow = 25))
for (i in 2:5) {
  yr = ydata[, (i-1)] %>% scale()
  p[i-1] = ar(yr, aic=TRUE)$order
  y = lag0(maxlag = p[i-1], yr) 
  x = lags(maxlag = p[i-1], yr) 
  l = ceiling(length(y)*0.8)
  y.train = y[1:l]
  y.test = y[(l+1):length(y)]
  x.train = x[1:l, ] 
  x.test = x[(l+1):dim(x)[1], ] %>% as.data.frame()
  arols = lm(y.train ~ x.train)
  cf = as.data.frame(lapply(arols$coefficients, rep, dim(x.test)[1])) # generate coef matrix
  fit.temp = cf[,-1] * x.test 
  fit.ar = rowSums(fit.temp) + cf[,1]
  out.mse.ar = mean((y.test-fit.ar)^2)
  mse[i-1] = out.mse.ar
  ar.info = arima(yr, order=c(25,0,0)) %>% coeftest()
  ar.info = ar.info[-26,c(1,4)] %>% round(digits = 4)
  ar.list[, (2*i-3):(2*i-2)] = ar.info
}
colnames(ar.list) = rep(c("Coefficients", "P-value"), 4)
rownames(ar.list) = paste0("ar", 1:25)
write.csv(ar.list, paste0("/Users/stanza/documents/github/lasso/ng/ar.csv"))
ar.table = cbind(p, mse)
colnames(ar.table) = c("Lags chosen by AIC", "M.S.E")
rownames(ar.table) = paste0("yr", 2:5)
pander(ar.table, caption = "AR")
```



```{r include=F, message=F, warning=F, echo=F, eval=F}
description = data.frame(`Short description` = c("hsmw",
                                   "hsbsou",
                                   "lhel",
                                   "fygt1",
                                   "exrjan",
                                   "exrcan",
                                   "lhu680",
                                   "ces003",
                                   "fclbmc",
                                   "ces140",
                                   "ces011",
                                   "ces002",
                                   "hsbmw",
                                   "pmcp",
                                   "pwimsa") ,  
           `Long description` = c("Housing Starts:Midwest(Thous.U.)S.A." , 
  "Houses Authorized By Build. Permits:South(Thou.U.)S.A.",
  "Index Of Help-Wanted Advertising In Newspapers (1967=100;Sa)",
  "Interest Rate: U.S.Treasury Const Maturities,1-Yr.(percentage Per Ann,Nsa)",
  "Foreign Exchange Rate: Japan (Yen Per U.S.$)",
  "Foreign Exchange Rate: Canada (Canadian $ Per U.S.$)",
  "Unemploy.By Duration: Average(Mean)Duration In Weeks (Sa)",
  "Employees On Nonfarm Payrolls - Goods-Producing",
  "Wkly Rp Lg Com'l Banks:Net Change Com'l & Indus Loans(Bil$,Saar)",
  "Employees On Nonfarm Payrolls - Government",
  "Employees On Nonfarm Payrolls - Construction",
  "Employees On Nonfarm Payrolls: Total Private",
  "Houses Authorized By Build. Permits:Midwest(Thou.U.)S.A.",
  "Napm Commodity Prices Index (Percent)",
  "Producer Price Index:I ntermed Mat.Supplies & Components(82=100,Sa)"), stringsAsFactors = FALSE) 
#%>% pander(justify = "left" , split.table = Inf , split.cell = 80, style = "grid", caption = "Data description")
write.csv(description, "description.csv")
```




